export enum Role {
  USER = 'user',
  MODEL = 'model'
}

export interface ChatAttachment {
  mimeType: string;
  data: string; // Base64 string (without data URI prefix)
  fileName?: string;
}

export interface ChatMessage {
  id: string;
  role: Role;
  content: string;
  timestamp: number;
  isStreaming?: boolean;
  isError?: boolean;
  attachment?: ChatAttachment;
  generatedImages?: string[]; // Array of base64 strings for images generated by the bot
}

export interface ModelConfig {
  id: string;
  name: string;
  description: string;
}

export interface UserProfile {
  name: string;
  email: string;
  picture?: string;
}

export interface ChatSession {
  id: string;
  title: string;
  messages: ChatMessage[];
  timestamp: number;
}

export interface Task {
  id: string;
  title: string;
  dueDateTime: string; // ISO string
  priority: 'low' | 'medium' | 'high';
  completed: boolean;
  notified: boolean;
}

export type ChatState = {
  messages: ChatMessage[];
  isLoading: boolean;
  selectedModelId: string;
};